### ISSUE TITLE
JSONC code blocks

### ISSUE THREAD

**Issue by jrappen** [facelessuser/sublime-markdown-popups#114]
Could you support `jsonc` code blocks by adding it to the mapping?

I switched to marking sublime `json` codeblocks in Markdown with `jsonc`, as `json` is strict `json` on GitHub and the necessity of having the old `javascript` workaround should've died long ago.

Sublime core now supports `jsonc` in Markdown after adding the branching support in v2 of syntaxes. Keith added it a short while back if I recall correctly, too lazy to look it up.

**Comment by rwols** [comment]
> the necessity of having the old javascript workaround should've died long ago.

What is so bad about using the `js` markdown language identifier?

**Comment by facelessuser** [comment]
I see nothing wrong with @rwols' suggestion, but with that said I'm not against a JSONC mapping either as I understand that some syntax languages may highlight things in a more preferable way.

Mapping can easily be updated via pull requests. If you desire a JSONC mapping, feel free to create a pull.

**Comment by rchl** [comment]
BTW. In JS a code that looks like an object (`{a: b}`) is parsed as a scoped block and code inside of it is parsed as statements. What's more, a key-value like lines are parsed as label statements.

In JSON/JSONC a plain object is parsed as an object with keys and values.

So the scopes and thus highlighting can vary a lot between those and the fact that JS syntax can even somewhat highlight such constructs is close to a miracle. :)

**Comment by jrappen** [comment]
@rchl thanks for #115
