### ISSUE TITLE
backslash-escaped newlines should result in <br> ?

### ISSUE THREAD

**Issue by rwols** [facelessuser/sublime-markdown-popups#119]
The pyright language server utilizes `\\n` to make a hard-break. However this doesn't seem to be handled by mdpopups:

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/2431823/108898625-b3ee5b00-7617-11eb-9806-5156b78aab22.png">

Associated markdown payload is

````
```python
class AMQPConnectionWorkflow()
```
---
Implements Pika's default workflow for performing multiple TCP/\[SSL\]/AMQP
connection attempts with timeouts and retries until one succeeds or all
attempts fail.

The workflow:\
&nbsp;&nbsp;&nbsp;&nbsp;while not success and retries remain:
        1. For each given config (pika.connection.Parameters object):\
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A. Perform DNS resolution of the config's host.
        B. Attempt to establish TCP/\[SSL\]/AMQP for each resolved address\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;until one succeeds, in which case we're done.
        2. If all configs failed but retries remain, resume from beginning\
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;after the given retry pause. NOTE: failure of DNS resolution
is equivalent to one cycle and will be retried after the pause
if retries remain.
````

translated from this rpc payload:

```python
{'sortText': '05.0000.AMQPConnectionWorkflow', 'documentation': {'kind': 'markdown', 'value': "```python\nclass AMQPConnectionWorkflow()\n```\n---\nImplements Pika's default workflow for performing multiple TCP/\\[SSL\\]/AMQP\nconnection attempts with timeouts and retries until one succeeds or all\nattempts fail.\n\nThe workflow:\\\n&nbsp;&nbsp;&nbsp;&nbsp;while not success and retries remain:\n        1. For each given config (pika.connection.Parameters object):\\\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A. Perform DNS resolution of the config's host.\nB. Attempt to establish TCP/\\[SSL\\]/AMQP for each resolved address\\\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;until one succeeds, in which case we're done.\n        2. If all configs failed but retries remain, resume from beginning\\\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;after the given retry pause. NOTE: failure of DNS resolution\nis equivalent to one cycle and will be retried after the pause\nif retries remain."}, 'kind': 7, 'label': 'AMQPConnectionWorkflow', 'data': {'position': {'line': 4, 'character': 9}, 'filePath': '/Users/raoulwols/dev/rabbitmqtest/myscript.py', 'workspacePath': '/Users/raoulwols/dev/rabbitmqtest', 'symbolLabel': 'AMQPConnectionWorkflow'}}
```

**Comment by facelessuser** [comment]
Did you enable `hardbreak` in `pymdownx.escapeall`? Now, that is some weirdly formatted stuff, so whatever Python Markdown does with that, good luck 🙃.

**Comment by rwols** [comment]
Nice. enabling hardbreak in pymdownx.escapeall does the trick.

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/2431823/108900392-dbdebe00-7619-11eb-9148-9bcface9700a.png">
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/2431823/108900537-03ce2180-761a-11eb-964d-9d131bcfde15.png">

````
```python
class PlainCredentials()
```
---
A credentials object for the default authentication methodology with
RabbitMQ.

If you do not pass in credentials to the ConnectionParameters object, it
will create credentials for 'guest' with the password of 'guest'.

If you pass True to erase\_on\_connect the credentials will not be stored
in memory after the Connection attempt has been made.

:param str username: The username to authenticate with\
:param str password: The password to authenticate with\
:param bool erase\_on\_connect: erase credentials on connect.
````

>  that is some weirdly formatted stuff

Tell me about it :D

**Comment by rwols** [comment]
By the way. I do notice the `<br>` bug from ST.

**Comment by facelessuser** [comment]
> By the way. I do notice the <br> bug from ST.

I have a CSS fix coming in the next few days. It was easy enough to patch the CSS to get sane results.

I've updated Python Markdown and Pymdown Extensions on the dependency repos (unreleased). The tip of Mdpopups has all the changes in it I plan on doing as well and should support the dependency updates.

I was looking at Markdown Preview which will be impacted by the dependency updates (they haven't been updated in so long, that there will be some breaking changes to some people just due to the length of time between the last updates). With that said, mdpopup users will hopefully not see any breaking changes as I've shoehorned in some deprecation paths. Maybe they'll see some warnings in the console if they are using an old extension like `pymdownx.extrarawhtml` which is no longer needed and accessible via `markdown.extensions.md_in_html` etc.

**Comment by rchl** [comment]
> I have a CSS fix coming in the next few days. It was easy enough to patch the CSS to get sane results.

Can you tell me more about it? I have the fear it won't be possible to fix that bug reliably with CSS because the behavior probably needs to be different whether the parent is a block or inline element.

Those should behave the same but they don't in ST.

view.show_popup('<style>br {display:block}</style><div>foo<br> bar</div>')
view.show_popup('<style>br {display:block}</style><span>foo<br> bar</span>')

**Comment by facelessuser** [comment]
> I have the fear it won't be possible to fix that bug reliably with CSS because the behavior probably needs to be different whether the parent is a block or inline element.

Can you explain your fear?  I see your examples, but I'm not understanding the concerns?

**Comment by facelessuser** [comment]
@rchl Maybe I should rephrase, what do you *think* should happen with these two scenarios? I'm getting the impression that you are perceiving these two scenarios should be handled in specific ways, which I am not certain is actually true.

**Comment by rchl** [comment]
I believe both should render the same way, with no extra leading space.

![Screenshot 2021-02-23 at 21 26 41](https://user-images.githubusercontent.com/153197/108903647-d3888200-761d-11eb-9bfe-e75b9e32dee4.png)

**Comment by facelessuser** [comment]
Yes, that is what I expect as well, and that is what I **thought** Sublime would do. But I guess I never specifically tested a `<br>` in an inline tag.

After testing these cases, it looks like minihtml does some further bizarre things and won't allow a block item to be block if it is inside a span. So, I'll rephrase, I fixed `<br>` in block cases, and Sublime has even more bugs with HTML handling that I cannot fix 🙃.

**Comment by facelessuser** [comment]
Ugh, try putting a `<p>` tag in a `<span>`, though not "proper" HTML, it will still render properly in a browser, but Sublime just made that content disappear for me 😬.

**Comment by rchl** [comment]
> So, I'll rephrase, I fixed `<br>` in block cases, and Sublime has even more bugs with HTML handling that I cannot fix 🙃.

But since you can't differentiate between block and inline cases, you can't really ship that fix as it will break the inline case, right?
Just clarifying because it isn't clear if you were planning to ship that fix or not.

**Comment by facelessuser** [comment]
> But since you can't differentiate between block and inline cases, you can't really ship that fix as it will break the inline case, right?

Ugh, I didn't realize that `<br>` broke to the next line in inline tags without setting them to `block`. Ugh, minihtml can be quite frustrating at times.

**Comment by facelessuser** [comment]
So, yeah, I can't ship that because the fix comes at a cost, where I thought it didn't.
