### ISSUE TITLE
Default.css location

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/sublime-markdown-popups#122]
Package Control 4.0 will move all dependencies to _Data/lib/python3x_ folders.

As a result, the curren [default.css](https://github.com/facelessuser/sublime-markdown-popups/blob/master/mdpopups_css/default.css) file will get lost.

It should therefore probably moved to _mdpopups_ python package. The library should ensure to be able to load it from _Data/lib/python33/mdpopups/_ once all dependencies are moved.

**Comment by facelessuser** [comment]
@deathaxe Will Package Control 4.0 immediately make dependencies in `Packages` void? Will there be a way to transition or will it just happen immediately on release of Package Control 4.0?

Hmm. I'm also assuming I won't be able to use `load_resources` to pull it in anymore...I don't think the Sublime API exposes the path to the installed location of Python dependencies either, so I guess I'll have to use some relative opening of the files based on my python `__file__` location.

**Comment by facelessuser** [comment]
Oh, will dependencies still have access to Sublime API?

**Comment by deathaxe** [comment]
As dependencies run in plugin host, I guess they still have access to `sublime` and `sublime_plugin` API as any other plugin.

`load_resource()` may not find resources in _Lib/..._ folders, that's true.

The current four-point-oh branch already contains an very early version of a "bootstrapper" which moves all dependencies from _Data/Packages/_ to _Data/Lib/python33/_ transforming them to "normal pip packages". This bootstrapper only moves contents of `st3` folder. Anything else is just dropped. I assume that to happen automatically and immediatelly once PC4.0 is released.

As the plan is to make all dependencies "pip compatible" I guess there won't be any chance for them to place plugin like content somewhere in _Packages_ except they do that themself. 

_Dependencies_ are also renamed to _Libraries_ to clarify their meaning.

At this point mdpopups is one of two known dependencies, which provide "plugin like extra content".

**Comment by facelessuser** [comment]
> _Dependencies_ are also renamed to _Libraries_ to clarify their meaning.

This naming, I assume, won't affect plugins declaring their dependencies in `dependencies.json` will it? PC isn't going to break things by requiring them to be specified in `libraries.json` are they?
