### ISSUE TITLE
FR: Allow text selection within popup

### ISSUE THREAD

**Issue by timfee** [facelessuser/sublime-markdown-popups#129]
Use case:

Sometimes I want to explicitly copy the inferred shape of an object to make it explicit. In vscode, I used to copy and paste from the popup window, but there doesn't seem to be a way to do this (I didn't see any `text-selection: none` in the generated CSS, so wasn't sure if this was controlled at a lower level).

<img width="661" alt="Screen Shot 2022-05-12 at 18 55 55" src="https://user-images.githubusercontent.com/3246342/168196161-701a09f0-445c-4963-9bde-5848564eb4e0.png">

**Comment by facelessuser** [comment]
Unfortunately, this is not something I can control. It's Sublime that does not allow text selection.

**Comment by facelessuser** [comment]
Closing as there is nothing we can currently do to mitigate this.
