### ISSUE TITLE
inability to persistently satisfy -mdpopups.py dependency

### ISSUE THREAD

**Issue by TSSlade** [facelessuser/sublime-markdown-popups#136]
I get a consistent / repeated "Installed missing dependency" error on every startup of Sublime
![2023-02-22_06h58_59](https://user-images.githubusercontent.com/3211478/220702185-f60ce870-68ab-4880-9336-c078704dd945.png)
The most salient output in the console is:
```
...stuff...
C:\Users\tslade\AppData\Roaming\Sublime Text\Installed Packages\Package Control.sublime-package\package_control/loader.py:294: UserWarning: Duplicate name: '-mdpopups.py'
Package Control: Installed missing dependency mdpopups
...stuff...
```
Following other documentation, I looked at the contents of `Sublime Text\Installed Packages\0_package_control_loader.sublime-package\` and I see the following:
```
-mdpopups.py
-mdpopups.py
00-package_control.py
01-pygments.py
08-portalockerfile.py
09-concurrentloghandler.py
10-debugtools.py
50-markupsafe.py
50-plantumlconnection.py
50-pymdownx.py
50-python-markdown.py
50-python-pywin32.py
50-pyyaml.py
51-python-jinja2.py
55-jsonschema.py
dependency-metadata.json
```

...that's after I deleted 175 instances of `-mdpopups.py` and invoked `Package Control: Satisfy Dependencies` before restarting Sublime.

**Comment by TSSlade** [comment]
Also attempted [this fix](https://forum.sublimetext.com/t/something-wrong-with-mdpopups-and-markdown/35129/4) (delete the `0_package_control_loader.sublime-package` and let ST rebuild it from scratch) and it was not successful.

**Comment by facelessuser** [comment]
Are you doing something custom? I do not control Package Control, nor how it loads packages. I have Sublime (with mdpopups) running on mac, windows, and linux without such issues. I'm not sure what you are experiencing.

**Comment by TSSlade** [comment]
I never got to the bottom of it. I *did* nuke my Sublime `User` folder and then systematically reintroduce all of the packages from my original installation, checking along the way whether the problem ever recurred. It never did, even with all the same packages installed.

So presumably there was just some manner of dependency corruption along the way that the `Satisfy Dependencies` command was never able to resolve...?

**Comment by facelessuser** [comment]
Okay, a local environment issue was really my only guess, and it appears to have been just that. Unfortunately, whatever the issue was, it is out of my domain. Regardless, glad you got it resolved.
