### ISSUE TITLE
Markdown parsing from LSP/Solargraph

### ISSUE THREAD

**Issue by dportalesr** [facelessuser/sublime-markdown-popups#139]
I have this code:

```ruby
# @return [Array<String, Integer>] The resulting array.
def payment
  ...
end
```

This is how the LSP popup looks on hover in a non-fresh install of ST4 (b4150) using solargraph

![deleteme-listing_search_resolver rb-20230802-021828](https://github.com/facelessuser/sublime-markdown-popups/assets/237597/9da984a3-9f38-4840-8f53-37b0a8351647)

And this is how it looks in a fresh install of ST3 (b3211)

![deleteme-abp-backend-20230802-021849](https://github.com/facelessuser/sublime-markdown-popups/assets/237597/27fa056d-6371-47d4-a34d-4eda25dc9c39)

Notice the escaped "<" for the return value. Also, it seems that ST4 is not recognizing the markdown list in that same section, whereas ST3 seems to be doing it (not sure if the line break is added because of the content).

I also tried it with Zed editor which also uses solargraph as LSP provider. This is what I expect to see:

![deleteme-abp-backend-20230802-023009](https://github.com/facelessuser/sublime-markdown-popups/assets/237597/5cfcd2e6-200d-41de-93d8-e03e855d4a67)
The additional spacing/line breaks between the sections are a nice addition but I don't really expect them in ST.

Let me know if this could be an issue from mdpopups issue or the LSP package or whatever. Maybe this could be solved by https://github.com/facelessuser/sublime-markdown-popups/issues/103 ?

**Comment by dportalesr** [comment]
From LSP log in ST:
```
[03:13:10.343] <<< ruby (3) (duration: 18ms): {'contents': {'kind': 'markdown', 'value': 'Payments::PaymentAffordability#payment\n\n`=^ Array<String, Integer>`\n\nReturns:\n* [Array\\<String, Integer\\>] The resulting array.\n\nVisibility: public'}}
```

**Comment by dportalesr** [comment]
Thank you very much for the comprehensive explanation.

So the markdown parsing is one issue won't be resolved anytime soon, it seems. What do you think about the additional/different escaping of the HTML characters (which somehow it ends showing just the first one)?

**Comment by facelessuser** [comment]
The original Markdown only stated that critical characters were escaped, such as `>` which are used as blockquotes. `<` was not part of the Markdown syntax, so it required no escaping. To have HTML brackets generally not parsed as actual HTML tags, it was expected that the user would use HTML entities.

Can MdPopups recognize backslash-escaped angle brackets? Sure, if the right extensions are enabled.

<img width="1246" alt="Screenshot 2023-08-02 at 3 09 42 PM" src="https://github.com/facelessuser/sublime-markdown-popups/assets/1055125/e73e135d-7689-4840-87e7-e85299e99b6c">

You need to this up with the LSP folks.

**Comment by dportalesr** [comment]
Gotcha!
