### ISSUE TITLE
Don't break long lines in source code

### ISSUE THREAD

**Issue by r-stein** [facelessuser/sublime-markdown-popups#14]
It would be nice, if it was possible not to break long lines, but make it horizontal scrollable instead. I am working on a Diff popup https://github.com/jisaacks/GitGutter/pull/296 based on this library and the popup gets confusing when the lines are to long:

![md_wrap_example](https://cloud.githubusercontent.com/assets/12573621/17995763/a7152246-6b64-11e6-8d21-8a20ddf77065.png)

**Comment by facelessuser** [comment]
Unfortunately, this may not be something I can control.  CSS like `overflow` etc. don't work in the minihtml it uses.  I believe the wrapping is controlled at the top level by the popup dialog itself, not the HTML CSS.  I can take a look, but I am pretty sure it is just going to end in disappointment, but I will give it try anyways 😉 .

**Comment by r-stein** [comment]
Ah thanks. I have played a little bit with the popup and it seems to break usual spaces , but not `&nbsp;`.
So I could just use `mdpopups.syntax_highlight` and replace the spaces, which are outside tags, with `&nbsp;`.

**Comment by facelessuser** [comment]
> So I could just use `mdpopups.syntax_highlight` and replace the spaces, which are outside tags, with &nbsp;.

I'm not sure I understand, but mdpopups, has to do some white space formatting for code blocks.  `pre` doesn't really work as a real `pre`, it is just a block html element in minihtml.  So I actually fake it internally.   If you are using `mdpopups.syntax_highlight`, it should at least format the content proper, anything outside of that will have to be formatted manually.

**Comment by facelessuser** [comment]
As for wrapping, I recommend setting `max_width` greater than you need.  Sublime sizes the dialog to smallest size it can, but by providing a `max_width` that is large, it can expand, without wrapping, up to that `max_width`.  If the screen is too small etc., Sublime will probably force a smaller window and wrap anyways.

**Comment by r-stein** [comment]
Thanks for that tip. That does in fact creates a bigger and better popup and might already be enough.

I meant one could write a html parser to convert the spaces into non breakable ones, i.e.
``` html
from:
<div class="highlight"><pre><span class="n">life_span_string</span> <span class="o">=</span> <span class="n">get_setting</span><span class="p">(</span><span class="s">"local_cache_life_span"</span><span class="p">)</span><br><span class="k">print</span><span class="p">(</span><span class="s">u"life_span_string: '{0}'"</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="nb">repr</span><span class="p">(</span><span class="n">life_span_string</span><span class="p">)))</span><br></pre></div>
to:
<div class="highlight"><pre><span class="n">life_span_string<span/>&nbsp;<span class="o">=<span/>&nbsp;<span class="n">get_setting<span/><span class="p">(<span/><span class="s">"local_cache_life_span"<span/><span class="p">)<span/><br><span class="k">print<span/><span class="p">(<span/><span class="s">u"life_span_string:&nbsp;'{0}'"<span/><span class="o">.<span/><span class="n">format<span/><span class="p">(<span/><span class="nb">repr<span/><span class="p">(<span/><span class="n">life_span_string<span/><span class="p">)))<span/><br><pre/><div/>
```

**Comment by facelessuser** [comment]
> I meant one could write a html parser to convert the spaces into non breakable ones, i.e.

Yeah, I guess, but why do it post instead of before?

**Comment by r-stein** [comment]
>> I meant one could write a html parser to convert the spaces into non breakable ones, i.e.
> Yeah, I guess, but why do it post instead of before?

How would I convert them before? If I just call `mdpopups.syntax_highlight(view, source_string.replace(" ", "&nbsp;"), "py")` it treats `&nbsp;` as python code and not as spaces.

**Comment by facelessuser** [comment]
Is `mdpopups.syntax_highlight` not converting the spaces for you?  It's supposed to search for any regions of multiple spaces and converter them to as shown (we will represent spaces with `.`): `_...` --> `.&nbsp;&nbsp;`.   Spaces collapse down to one, so we only convert spaces if they exceed 1 in a row. You shouldn't have to convert anything; it should be done for you.

By doing what you are, you are, you are sending in text, not an actual `&nbsp`.  Since `mdpopups.syntax_highlight` preserves the raw text, you can see why this is a problem.  If you sent in the actual character for `&nbsp`, then that would possibly work, but you shouldn't have to.

**Comment by facelessuser** [comment]
Hmm, maybe you are saying you wanted **all** spaces and not just **extra** spaces converted to `&nbsp;`?  `...` --> `&nbsp;&nbsp;&nbsp;` instead of `...` --> `.&nbsp;&nbsp;`?

**Comment by r-stein** [comment]
Now I understand it and `source_string.replace(" ", "\u00a0")` does the job. Thanks a lot.

**Comment by facelessuser** [comment]
Do please let me know if the described functionality was working.  Do you think it would be beneficial to force all spaces to non breaking spaces in block code (not inline of course)?

**Comment by r-stein** [comment]
It works as expected and is super easy.
I am not sure if it would be better to force all spaces (in code blocks) to be non-breakable. I tend to say "yes", because it is usually (github, stackoverflow,...) done like this and a wrong wrapping can potentially change the meaning of the code.

**Comment by facelessuser** [comment]
I'll experiment and see. Thanks.

**Comment by facelessuser** [comment]
Moving forward, mdpopups will not break block code lines: https://github.com/facelessuser/sublime-markdown-popups/commit/2e8ff03f33ac89b1c13bde282c3fb784070fce2a.

**Comment by r-stein** [comment]
Nice =) This would be version `1.11.0` and newer?

**Comment by facelessuser** [comment]
Yes. I will probably release it today.

**Comment by facelessuser** [comment]
It's released, so you can pick it up by either letting Package Control update it when it feels like it, or run `Satisfy Dependencies`.

**Comment by r-stein** [comment]
Ok, thanks a lot.
