### ISSUE TITLE
Installation with git

### ISSUE THREAD

**Issue by stoivo** [facelessuser/sublime-markdown-popups#16]
I have a small question. 
I had some problem install in mdpopups with git.

I fould out that I need to install it in mdpopups and not sublime-markdown-popups. When I changed this it works. Is this correct or should it work with both names? 

Is there something more I should do if I want to install it with git?  Maybe there is some documentation you can point me at.

**Comment by facelessuser** [comment]
Can I ask why you need to install via git?

**Comment by stoivo** [comment]
I am working on GitSavvy

**Comment by stoivo** [comment]
Also I like to read the source code, and then maybe send patches :)

**Comment by facelessuser** [comment]
This is how I work, I add the mdpopups dependency to my package and let Package Control pull down the  package.  The difference is that I add a package channel to Package Control that instructs Package Control to use the tip of the mdpopups branch.  I make changes to the local copy that Package Control pulls down, and when I verify it is working, I merge the changes over to the git checkout version and commit.

In Package Control setting file:

```
	"repositories":
	[
		"https://raw.githubusercontent.com/facelessuser/SublimeRandomCrap/st-dev-repos/repositories.json"
	]
```

I have a testing repo called SublimeRandomCrap, and I created a branch under that project that contains the `repositories.json` file.

It is easier for me to approach it like this than trying to generate the meta data for the dependency and tricking Package Control to load it (or load it myself properly like Package Control does -- though I do know how to do that as well and I have documented that somewhere...).  I usually just diff the Package Control version with my Git version and merge the changes.

**Comment by facelessuser** [comment]
FYI, manual install info.  Maybe it could be adapted to a git install: https://github.com/facelessuser/BracketHighlighter/issues/293#issuecomment-233109077.

**Comment by stoivo** [comment]
I use many of your packages and am grateful for you work. Thanks for the great work!!

I believe that you have a good workflow. I would like to try out the same workflow as you have. How is your workflow when working on BracketHighlighter? Do you clone it with git and then amend it there? How are you sure you are pulling mdpopups from your repositories.json and not packagecontroll.io 's? 


Thank for spending your spare time explaining to people like me :D

**Comment by facelessuser** [comment]
> I use many of your packages and am grateful for you work. Thanks for the great work!!

Thank you.

> I believe that you have a good workflow. I would like to try out the same workflow as you have. How is your workflow when working on BracketHighlighter? Do you clone it with git and then amend it there? How are you sure you are pulling mdpopups from your repositories.json and not packagecontroll.io 's?

I work directly with the git checkout of non-dependency packages that I support, so I am manually managing those through the github app.  I am always running locally with the latest (tip of main) dependencies (that I provide).  Package Control (using my channel) will keep me up to date (in theory), but Package Control doesn't always update when its supposed to, so then I run the `Satisfy Dependencies` command from command palette to ensure I have the latest.

It is possible that if one of the packages that use the dependencies updates through Package Control, that the dependency will update (assuming I am not already on the latest commit), but since Package Control doesn't manage the packages I develop (I manually manage those), it isn't a problem.  Also, I am usually already on the latest commit.  It isn't perfect, but so far it works well for me.

**Comment by facelessuser** [comment]
> How are you sure you are pulling mdpopups from your repositories.json and not packagecontroll.io 's?

I originally was using Package Control's latest version.  I ran Satisfy Dependencies, and it did nothing.  I added my channel, and ran Satisfy Dependencies, and this time it pulled down a new copy of mdpopups.  I looked at the source and confirmed it was the latest.  After that I was confident in it and have been using it that way since.

**Comment by stoivo** [comment]
Thank again. I will play around. If I face something I don't understand is it ok if I ping you here?

**Comment by facelessuser** [comment]
Not a problem.  Ask away.   It's kind of awkward working with dependencies, so I understand.

**Comment by stoivo** [comment]
Where can I find documentation on dependencies.json should look?

**Comment by facelessuser** [comment]
> Where can I find documentation on dependencies.json should look?

https://packagecontrol.io/docs/dependencies

You can also look at examples of packages that use them.

**Comment by stoivo** [comment]
Sorry to bug you again.

I have created a repositories.json  https://raw.githubusercontent.com/stoivo/sublime_bug_demo/packages/repositories.json .
Then I created a small plugin to test it https://github.com/stoivo/sublime_bug_demo/tree/debug_version. Same repo with an other branch.
Also added
```
	"repositories":
	[
		"https://raw.githubusercontent.com/stoivo/sublime_bug_demo/packages/repositories.json"
	]
```

to `Package Controll.sublime-settings`

Still when I open `Package Control: Install Package`, I can't fine my package. Any ideas?

**Comment by FichteFoll** [comment]
Is the package already installed/does it exist? 

Also, you can point to local files on your dist in the `repositories` key iirc.

**Comment by facelessuser** [comment]
Which package, and like @FichteFoll asked, is it already installed, because if so, you don't need to install it.  Just run satisfy dependencies to get the dependencies.

**Comment by stoivo** [comment]
Hello

Sorry for not updating you, it took me some time to find that I had a syntax error in 'repositories.json' that make it invalid for sublime but chrome parses it correctly.

If you are interested the error has corrected in this commit https://github.com/stoivo/sublime_bug_demo/commit/e5eff6f097fae65fdf499be3057fee25c84291d3

**Comment by facelessuser** [comment]
Ah, yeah, strict json parsers don't like trailing commas.
