### ISSUE TITLE
Invalid CSS variables freeze cursor or crash ST

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/sublime-markdown-popups#29]
Can you have a look at https://github.com/SublimeTextIssues/Core/issues/1697 please. There is something wrong, when using CSS variables with mdpopups. They cause ST to crash.

**Comment by facelessuser** [comment]
I don't understand your issue.  I looked at the linked issue, but I see you are using a template variable that is commented out.  You also aren't using mdpopus template vars currectly if it is just `{{font_face}}`.  Plugin template vars should be under `plugins.font_face` from what I remember.  Is that why you are having issues?

Are you on the latest release or the tip of master? If you are at the tip of master with the unreleased stuff, you can try setting: `--mdpopups-font-mono`.

In my opinion, you shouldn't really be making font face decisions for a user.  The next release will force a generic monospace font that is likely to be on most people's systems, and the user can specify a specific, desired monospace font in their `mdpopups.css`; this is what I do.  If I were you, I'd just document that for 2.0 mdpopups.

Please elaborate if I'm missing something.

**Comment by facelessuser** [comment]
I think I understand the point of the issue now that I've thought about it a little more.  You are looking for a clean way to exit with a bad variable.  I can at least look into a way to handle bad Jinja2 variables, but I don't recall them crashing Sublime, but I will check.  I can't do anything about how Sublime handles bad CSS variables.  That is out of my control, and if that is what is meant here, I will have to leave this up to Sublime and close this issue.

I would still consider my comments about letting the user define their own mono font in `mdpopups.css`.  While I'll allow a plugin now to change whatever they want, I would be upset with a plugin playing with my font when I can easily control that myself (at least when mdpopups 2.0 comes out).

**Comment by deathaxe** [comment]
Hmm, where to start?!

### Version

> Are you on the latest release or the tip of master?

The crash happens with both latest release and master.

### Font Face

> ... you can try setting: --mdpopups-font-mono

This looks terribly ugly on Windows 10.

> In my opinion, you shouldn't really be making font face decisions for a user. 

This is very correct in general. Font settings are part of the theme normally.

But the font_face of the view is not part of the theme but of the user settings. Therefore the font-family of diff popup's content should adapt to the "font_face" setting in "Preferences.sublime-settings" **by default**, if the theme or user did not set anything else in its stylesheet.

_I don't want to need to edit the stylesheet, if I decide to change the font settings._

GitGutter diff popup is used to show some recent piece of content (text or source code) of the view. The content is already highlighted using the view's color scheme by mdpopups. Why not use the view's font_face by default to show that content if the colors already match? 

_It would be very enough to have a {{var.font_face}} template variable which provides the view's "font_face"._

It can be used by any stylesheet which wants to adapt to the view's font settings, even by theme authors.


> You also aren't using mdpopus template vars currectly if it is just {{font_face}}.

Please don't worry about that detail. ;-) Current release of GitGutter calls jinja directly to create the css - that's correct.

But I started to work with `template_vars` and already passed {{plugin.font_face}} successfully as follows.

#### Part of _gitgutter_popup.css_

```css
.git-gutter .highlight {
    margin: 0.0rem;
    border-radius: 0.25rem;
    font-family: "{{plugin.font_face}}";
}
```

#### Part of code being used

```python
jinja_kwargs = {
    'font_face': view.settings().get('font_face', 'monospace')
}

return mdpopups.show_popup(
    view, content, md=False, css=css, wrapper_class=wrapper_class[1:],
    location=location, max_width=max_width, flags=flags,
    on_navigate=navigate, template_vars=jinja_kwargs)
```


### Crash of ST

I just tried to use the template to create a _css variable_ which should than be used by all other selectors. This might not be useful or not required. I did so just to see what's possible without thinking about how useful it is.

In fact by just changing the following one line in the css causes ST to freeze the cursor if mdpopups.show_popup() is called and crashes ST with mdpopups.update_popup() being called if `--font-face` is not defined anywhere.

```css
.git-gutter .highlight {
    margin: 0.0rem;
    border-radius: 0.25rem;
    font-family: var(--font-face);   /*"{{plugin.font_face}}";*/
}
```

I actually can't say for sure who to blame for the crash in the end.

Passing the stylesheet merged with the content directly to `sublime.show_popup()` works fine, but I am not aware of the tags being wrapped around `css` and `content` by mdpopups, so I might be misled.

It causes an access violation and crashs ST - not sure whether this is actually a problem of the core or any library being used by mdpopups.

**Comment by facelessuser** [comment]
> This looks terribly ugly on Windows 10.

What do you mean this looks terrible ugly on Windows 10?  Are you talking about the font in the example? It's just a font setting, set it to whatever you like.

> But the font_face of the view is not part of the theme but of the user settings. Therefore the font-family of diff popup's content should adapt to the "font_face" setting in "Preferences.sublime-settings" by default, if the theme or user did not set anything else in its stylesheet.

Fonts currently **do** come from the view in the current release, but recent unreleased builds I force a monospace font.  See issue #24.  Code blocks are always styled monospace fonts in almost every Markdown output you see out there.  But sublime views are not always monospaced due to a user's settings.  A user, or plugin (in 2.0) can set `--mdpopups-font-mono` to whatever they want, even the view's font if desired.  And if you do it in the plugin, a user can override that in `mdpopups.css`.  I think this is reasonable.

> In fact by just changing the following one line in the css causes ST to freeze the cursor if mdpopups.show_popup() is called and crashes ST with mdpopups.update_popup() being called if --font-face is not defined anywhere.

I don't control CSS variables, that is a Sublime API thing.  If you access a CSS variable that isn't defined, Sublime needs to handle that, not mdpopups.  Mdpopups as no way of knowing if you are using a variable that is defined in a color scheme (that it can't see) or not.  I can't protect against this.  Sublime needs to do this gracefully.

Now I can probably start dumping info on bad Jinja variables, but I can't control sublime CSS variables.

**Comment by deathaxe** [comment]
> I don't control CSS variables, that is a Sublime API thing. If you access a CSS variable that isn't defined, Sublime needs to handle that, not mdpopups. 

I totally agree. I just asked to have a look on it, as I was not able to reproduce using the normal popup API. So the core devs might point to mdpopups. I don't know which parts of the css/content is handled by mdpopups and where the reason is caused. I involved you as you know the internals of mdpopups better than me.

**Comment by facelessuser** [comment]
So when no CSS variable is defined without mdpopups, it works?  That is weird.  I don't know what I would be doing differently with those.  I'll take a look, but I can't promise anything.

**Comment by facelessuser** [comment]
I can crash Sublime with the code below.  This has nothing to do with mdpopups.

```py
import sublime

sublime.active_window().active_view().show_popup(
    """<body id="my-plugin-feature">
    <style>
    div {
        font-family: var(--does-not-exist);
    }
    </style>
    <div>Text</div>
    </body>
    """
)
```

**Comment by facelessuser** [comment]
I'm closing this as this is not an mdpopups issue.
