### ISSUE TITLE
Plans to add body-tag to follow best practice?

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/sublime-markdown-popups#30]
Do you plan to follow the _Best Practice_ example to wrap everything into a `<body id="...">` tag some day?

Not that I wish this change, as it might cause backward compatibility issues. Just to know if you do.

See: https://www.sublimetext.com/docs/3/minihtml.html

```html
<body id="my-plugin-feature">
    <style>
        div.error {
            background-color: red;
            padding: 5px;
        }
    </style>
    <div class="error"></div>
</body>
```

**Comment by facelessuser** [comment]
Not really. I like how it is now.
