### ISSUE TITLE
Is there an packagecontrol.io plugin?

### ISSUE THREAD

**Issue by tobiashochguertel** [facelessuser/sublime-markdown-popups#31]
I wan't to test this Plugins, but I can't get it running with this source code checked out under  `%APPDATA%/Sublime Text 3/Packages/mdpopups`.

It looks like that the plugin is loaded but it has no effect?

Can you help me?

**Comment by facelessuser** [comment]
So, I currently don't have enough information to go on.  What version of Sublime are you on?

1. You have to have, for the most recent version, at least 3124.  I've recently dropped legacy support for anything below that level.

2. I don't recommend manually installing the source.  If you have a plugin that uses it, you should have it locally for free.  For instance, if you are on ST 3124+ and have BracketHighlighter, you should already have it.  If you don't have any plugin that relies on this, then you will have add support in a plugin to pull it. This is a tool to be incorporated during plugin development.  Not usually something you pull down by itself.

3. Luckily it is easy to add this as a dependency to a plugin and remove it.  This is something I probably need to make more clear in the docs, but if you create a `dependencies.json` file in the root of your plugin with the following content and run `Package Control: Satisfy dependencies`, Package Control will pull it down and create a special plugin that loads it **before** all other plugins.

    ```js
    {
        "*": {
            ">=3124": [
                "pygments",
                "python-markdown",
                "mdpopups",
                "python-jinja2",
                "markupsafe"
            ]
        }
    }
    ```

4. After that, just use the API to show a popup in the view.  You can run this from the console if you like, or incorporate actual code into your plugin.

    ```python
    import mdpopups

    view = sublime.active_window().active_view()
    mdpopups.show_popup(view, '# This is a test!\n\nHello World!\n')
    ```

5. To remove `mdpopups`, assuming you never added actual code to your plugin, just remove the `dependencies.json` file from your plugin and run `Package Control: Satisfy dependencies` again and Package Control will see that no plugins are using `mdpopups` and remove it.  This assumes that no other plugins are using `mdpopups`.

6. Now if you already have a plugin that requires `mdpopups` you should already have it.  And you can just run `Package Control: Satisfy dependencies` to get the latest if Package Control hasn't updated it recently for you.

Hopefully that makes it clear.  I won't go into what I do to develop `mdpopups` locally right now, just what developers can do to start playing with it.
