### ISSUE TITLE
Question regarding dependencies.json

### ISSUE THREAD

**Issue by underscorediscovery** [facelessuser/sublime-markdown-popups#5]
This plugin looks really promising!

I tried to test it out and followed the Installation/Dependencies in the docs, 
my dependencies.json matches the one shown in the docs. 
However this is what sublime says in console (and a popup alert):

```
Package Control: Installing 4 missing dependencies
Package Control: Installed missing dependency markupsafe
Package Control: The dependency specified, markdown, is not available
Package Control: Installed missing dependency pygments
Package Control: The dependency specified, jinja2, is not available
error: Package Control

2 missing dependencies were just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
```

I looked on Package Control for the related packages but none of them were listed, am I missing something fundamental here?

**Comment by facelessuser** [comment]
You actually caught me on my computer.  So the documentation  is a little bit out of date, whoops!

```js
{
    "*": {
        ">=3000": [
            "pygments",
            "python-markdown",
            "mdpopups",
            "python-jinja2",
            "markupsafe"
        ]
    }
}
```

**Comment by facelessuser** [comment]
Updated docs.  Just change your dependencies, and run "satisfy dependencies" command from Package Control.

**Comment by underscorediscovery** [comment]
Seems to have done the trick, thanks for the quick response!

**Comment by facelessuser** [comment]
FYI, it should probably be `>=3080` as ST3 didn't have a public beta with tooltips until right about then, but glad you got it working.

**Comment by underscorediscovery** [comment]
Yea I bumped it up already thanks :)
