### ISSUE TITLE
mdpopups package missing from package control

### ISSUE THREAD

**Issue by sammcj** [facelessuser/sublime-markdown-popups#55]
Looks like the `mdpopups` package is missing from Sublime Package Control

- https://packagecontrol.io/search/mdpopups returns no result.
- Searching for the package using install package within sublime text returns no result.

**Comment by sammcj** [comment]
ugh, ok sorry I didn't RTFM properly ;)

**Comment by CaitlinWeb** [comment]
I'm still having this issue. I don't see it in Package Control.

**Comment by facelessuser** [comment]
@CaitlinWeb, Please see http://facelessuser.github.io/sublime-markdown-popups/installation/#package-control and http://facelessuser.github.io/sublime-markdown-popups/api/#dependencies.  This is not a package, but a dependency.
