### ISSUE TITLE
Package unavailable at packagecontrol.io

### ISSUE THREAD

**Issue by Romarain** [facelessuser/sublime-markdown-popups#56]
Hi,
I'm sorry, I had to post this here because I found no e-mail address in your GitHub profile : your project is no more available at [packagecontrol.io](https://packagecontrol.io), and I would like to let you know.

I suppose we can just clone your depot in the packages folder of ST3, but it could be helpfull to have it available in the _Package Control_ installer of ST3.

By the way : I'm here because it seems that ColorHelper now requires to install "mdpopups" to work properly. I've just installed _ColorHelper_ in my ST3, and the **little colored squares** don't show up, wether `inline_previews` is set to `true`.

**Comment by facelessuser** [comment]
It's not a package, but a dependency for packages: http://facelessuser.github.io/sublime-markdown-popups/installation/#package-control.

Make sure to restart Sublime after installing a package with dependencies to ensure all dependencies are loaded properly.  If dependencies are not installed, you can run `Package Control: Satisfy Dependencies` to install them.  Watch the console to get status of installation completion, and then restart Sublime.

**Comment by BarbzYHOOL** [comment]
Then is it normal that it's not listed in my package list?

And how to test if it's correctly installed? I have gitgutter but I can't do like their gif

https://raw.githubusercontent.com/jisaacks/GitGutter/master/docs/assets/images/diff_popup.gif
