### ISSUE TITLE
Wrong mapping for TypeScript :D

### ISSUE THREAD

**Issue by predragnikolic** [facelessuser/sublime-markdown-popups#57]
Hello I noticed a wrong mapping TypeScript.
I have [TypeScriptSyntax](https://github.com/braver/TypeScriptSyntax) installed.

[Here](https://github.com/facelessuser/sublime-markdown-popups/blob/ae6d4f27da8f5bf85fff270cbdd9780770ee48f2/st3/mdpopups/st_mapping.py#L52) instead of `'TypeScriptSyntax/TypeScript'` should be `'TypeScript Syntax/TypeScript'`.

```
>>> view.settings().get('syntax')
'Packages/TypeScript Syntax/TypeScript.tmLanguage'
```

This issue is realated to tomv564/LSP#383

Before the change it was like this.
![2018-08-09-112406_683x384_scrot](https://user-images.githubusercontent.com/22029477/43890363-d4657fe0-9bc6-11e8-999b-da7650767e7b.png)
And after changing.
![2018-08-09-112340_683x384_scrot](https://user-images.githubusercontent.com/22029477/43890375-dc847ca8-9bc6-11e8-98a4-a27c1e0f3fe4.png)

**Comment by facelessuser** [comment]
I'll take a look at this sometime soon.  Sorry I missed this.

**Comment by predragnikolic** [comment]
No problem. 

But when you get to this, maybe you could also add support for `rust` in the mapping file?

That's all from me for now.

**Comment by facelessuser** [comment]
If you find me the syntax to add for rust, is be happy to look at it.

**Comment by predragnikolic** [comment]
I just added this line `'rust': (('rs', 'rust'), ('Rust/Rust',)),` to the `lang_map` variable in the `st_mapping.py` file.

**Comment by predragnikolic** [comment]
Sorry accidentally pressed `ctrl+shift+enter`. Apparently that shortcut leaves a comment, and closes the issue.  
Just wanted to say that the full name of the syntax for rust is 'Packages/Rust/Rust.sublime-syntax'.

**Comment by facelessuser** [comment]
Cool. I try to get to it when I can, but pull requests are also welcome.
