### ISSUE TITLE
Showcase/Where used

### ISSUE THREAD

**Issue by KyleKing** [facelessuser/sublime-markdown-popups#58]
I think it would be great to see plugins built on this package. Just something simple like this:

## Showcase

[facelessuser/ColorHelper](https://github.com/facelessuser/ColorHelper)
[flashios09/GitGutter](https://github.com/flashios09/GitGutter)
[SublimeText/LaTeXTools](https://github.com/SublimeText/LaTeXTools)
[Kronuz/SublimeCodeIntel](https://github.com/Kronuz/SublimeCodeIntel)
[phil65/KodiDevKit](https://github.com/phil65/KodiDevKit)

**Comment by facelessuser** [comment]
Sorry I haven't gotten to this in a bit, but I am cool with this.  If I get a chance, I'll do it, but pull requests are welcome.

**Comment by facelessuser** [comment]
This will be noted in the documentation on the next release
