### ISSUE TITLE
Default Padding/Margin

### ISSUE THREAD

**Issue by underscorediscovery** [facelessuser/sublime-markdown-popups#6]
When showing the basic popup, 
`mdpopups.show_popup(view, 'hmm')`

The spacing is as follows:

![screen 2015-11-21 at 8 04 01 pm](https://cloud.githubusercontent.com/assets/236374/11321051/29346418-908b-11e5-84be-0f6e3265423a.png)

I've tried the various paddings and margin `css=''` injected options to try and reduce that spacing, but nothing seems to be affecting it. I've checked the base.css and related files but can't find any suspicious places to prod.

Any hints?

**Comment by facelessuser** [comment]
Might just be a sublime thing.  When I set the margins, the side margins change,  but we might be stuck with top and bottom.  I'll double check when I get some time to confirm.

**Comment by underscorediscovery** [comment]
The default `view.show_popup` doesn't have it, for interest sake.

![screen 2015-11-21 at 4 10 20 pm](https://cloud.githubusercontent.com/assets/236374/11321144/9863f338-908d-11e5-84de-fe52b4aae5c0.png)

**Comment by facelessuser** [comment]
Okay,  I'll take a look. Possible maybe paragraph elements have a big margin the markdown gets wrapped in paragraphs.

**Comment by underscorediscovery** [comment]
```
MarkdownPopup: =====HTML OUTPUT=====
MarkdownPopup: <p>hmm</p>
```

Here's what the debug output has,
I should be easily able to get by with that info for now.

**Comment by facelessuser** [comment]
Cool, we can probably tweak the base CSS to make it less severe out of the box.

**Comment by underscorediscovery** [comment]
Digging into the debug printed css, 
(I'm assuming the css is order dependent in minihtml)
Wouldn't the injected css be too early here?
Note how `body` has the `padding:1em` but I wouldn't be able to override it because note where the `p { }` is that I pushed (via `css=` named param)

![screen 2015-11-21 at 8 30 27 pm](https://cloud.githubusercontent.com/assets/236374/11321189/e787f3c8-908e-11e5-9abd-2597b0d23049.png)

**Comment by facelessuser** [comment]
So we have 3 kinds of CSS:

- base: this is always first and is mainly just formatting stuff.
- plugin-injected:  this is mainly to style new stuff, not to override current stuff; I don't want a plugin coming in and changing my styles.
- user-css: this overrides all and is always last.  It is called default.css, but you can override it by putting a mdpopups.css in your user folder.

User gets the last say, not some random plugin.  Ideally, a plugin would document their special classes, and if a user wanted to override it, they would in their user css.

Does that make sense?  I am open to discussion on it.  That was just my current approach.

**Comment by underscorediscovery** [comment]
In the above case then, the really large 1em padding on the body is unusable for single line tooltips and imo should be 0.1 or a config.

I quite dislike that the apparent model here is global (see the preferences, when I view these as invocation level config, i.e plugin specific). I 100% agree on the user preferences, but if this is a tool for plugin developers the global patterns are going to bother me. 

I've only just started playing with this, evaluating it if it would be able to express _explicit_ and _crafted_ output while still respecting the user preferences.

In this specific instance, I would actually classify it 4 kinds. 

- base
- default
- plugin specific
- usercss

I don't know what the difference is between default and base, but in the above instance not being able to override the defaults for the plugin specifics doesn't feel like respecting _the end users preference_ because they haven't made one yet.

**Comment by facelessuser** [comment]
To be honest, the 1em padding should not be in default.  It should be in base, but I agree it should probably be something different.  Base is supposed to be basic formatting. to make the tooltip look okay (no color stuff).  Default was supposed to be superficial and strictly color stuff.

I don't think a 4th plugin type is necessary.  User actually replaces default (but keep in mind there is some caching involved).

**Comment by underscorediscovery** [comment]
Yea I was speaking conceptually with the 4 types, never mind that.

How it is now is perfectly fine with "sane defaults", 
the plugin can make some executive calls on formatting (this is my concern),
but the user still has the last say with their own css (this is as important).

**Comment by facelessuser** [comment]
> How it is now is perfectly fine with "sane defaults", 

Understood.  I believe most of them are "sane", but I think `body` padding should be moved to base and probably be less and `p` padding/margin (not sure which is the problem), should be less severe.  I am open to a proposal.  Also I have a couple other paddings in the default that should be moved.

> the plugin can make some executive calls on formatting (this is my concern),

They can and should be able to.  The few paddings in the default were simply oversights on my part.  This is a pretty new dependency.  And as more people use it, things like this are going to get exposed.  I think by moving the padding to the base and fixing it to more "sane", should solve all your problems.

**Comment by underscorediscovery** [comment]
Yep, agreed.
If there are things to PR I can whip some up, 
though it might be simpler in this instance to do your thing if you were down there.

**Comment by facelessuser** [comment]
I'll take a stab at it and put it up on the main branch.  I'll let you play with it locally and give feedback.  Once we agree on the base format, I make a release.  I'm sure there will be other formatting quirks that will get exposed in time, but we will deal with them then.

Thanks for your input, it was very helpful.

**Comment by facelessuser** [comment]
> !important breaks the popup :)

Oh, yeah.  The ST3 CSS engine sucks.  Like a lot.  so don't try and do anything too fancy :).

**Comment by facelessuser** [comment]
Okay, so I committed some CSS changes. Keep in mind paragraphs need margins at the bottom.  And since I can't target last child elements with the crappy CSS engines, I can't tell it to ignore padding on the last one.  Here is what I am using to test:

    test_content = '''
    # H1
    ## H2
    ### H3
    #### H4
    ##### H5
    ###### H6
    Testing **bold** text and testing *italic* text.
    Testing autolink: www.google.com.
    Testing inline `code`.

        Testing indented code blocks

    ```
    Testing a fenced block.
    ```

    > Testing
    > Blockquotes

    Testing
    :   Description

        Lists

    - Testing lists
        - Testing lists
        - Testing lists

    - Testing ordered lists (ST will not show numbers :()
        1. Testing lists
        2. Testing lists

    - **Test** inline highlight ```:::python yield 0, '<code class="%s">' % self.cssclass```.
    - *Test* fenced highlight

        ```python
        class SublimeInlineHtmlFormatter(HtmlFormatter):
        """Format the code blocks."""

        def wrap(self, source, outfile):
            """Overload wrap."""

            return self._wrap_code(source)
        ```

    ---

    !!! danger "Tip"
        Testing, admonition blocks.

    !!! tip "Tip"
        Testing, admonition blocks.

    !!! attention "Tip"
        Testing, admonition blocks.

    !!! caution "Tip"
        Testing, admonition blocks.

    !!! danger "Tip"
        Testing, admonition blocks.

    !!! note "Tip"
        Testing, admonition blocks.
    '''

Feel free to let me know what you think.

**Comment by facelessuser** [comment]
Changes are here for reference: https://github.com/facelessuser/sublime-markdown-popups/commit/202e0f7181cfbf57c165a68218e216c671f70d75.

**Comment by underscorediscovery** [comment]
Yea I don't see any specifics that would get in the way at a glance, looks good, thanks!
I'll try coerce sublime to use a cloned copy and see if I can test it.

**Comment by underscorediscovery** [comment]
So that's definitely better.
I can get down to no invasive padding which is perfect for me:

![screen 2015-11-21 at 10 19 45 pm](https://cloud.githubusercontent.com/assets/236374/11321533/122cd346-909e-11e5-9f23-a71da6ee4c54.png)

From this end it looks great. 
Whenever the release goes user facing to package control,
I'll probably push an update using it for my users to hammer on too.

Thanks for the tweaks.

**Comment by facelessuser** [comment]
> EDIT: seems it's unpacked in my folder, so I can just replace the changed files.

yup

Probably remove the wrapper div here too https://github.com/facelessuser/sublime-markdown-popups/blob/master/st3/mdpopups/__init__.py#L280.  That div is unnecessary and will add additional padding.

**Comment by underscorediscovery** [comment]
Ah yea that may play a part, I muted `div` margin as well so I might not have seen it but since it's hidden from the `=====HTML OUTPUT=====` output I didn't see it either.

**Comment by facelessuser** [comment]
I'll remove the div and I'll push it out tonight.

**Comment by facelessuser** [comment]
[`1.3.1`](https://github.com/facelessuser/sublime-markdown-popups/releases/tag/1.3.1) released.  Just run the "satisfy dependecy" command from package control and you should be good to go.

**Comment by underscorediscovery** [comment]
Yep looks great. I released my end, everything looks solid so far.
I'll be trying something a bit more elaborate tomorrow so I'm sure I'll have more feedback.

Thanks again.

**Comment by facelessuser** [comment]
No problem.  Glad you are finding it useful.
