### ISSUE TITLE
themes?

### ISSUE THREAD

**Issue by kud** [facelessuser/sublime-markdown-popups#69]
It could be great if there were a bunch of themes availables there. :D

**Comment by facelessuser** [comment]
The idea was to actually give consistent styling across plugins by using your current theme, with the option for plugins to provide some additional CSS for plugin specific controls.

When you say different styles, are you suggesting formatting and such? Or colors? For the latter, that kind of goes against what is attempting to addresses with this plugin.

With all of that said, a user can override the default CSS work anything they prefer.

I'm not entirely sure what specifically you'd like to see. Maybe a mock up might help?

**Comment by kud** [comment]
You're right :)

I was just thinking about user contributions to have a better popup even if it's compliant to your theme.

**Comment by facelessuser** [comment]
I don't mind improving the pop-up, but I need to kind of see the improvement :).

**Comment by kud** [comment]
I understand the I don't see neither the improvement in fact. I was just a bit lazy to custom myself the popup and wanted to see some community theme releases. :D

**Comment by facelessuser** [comment]
Since the default can be overridden, there could be community themes. You'd just have to use the settings to override the default. I wouldn't formally have them here, but I wouldn't mind printing people to them.

I'm also willing accept pulls for improved default popups :).
