### ISSUE TITLE
How to fix tooltip links?

### ISSUE THREAD

**Issue by jrappen** [facelessuser/sublime-markdown-popups#7]
```markdown
[test](https://www.google.com/search?hl=en&q=test)
```

passed as part of `tooltip` into:

```python
mdpopups.show_popup(view, '\n'.join(tooltip),
    css='default.css',
    flags=sublime.COOPERATE_WITH_AUTO_COMPLETE,
    location=-1, max_width=600, max_height=350,
    on_navigate=self.on_navigate
)
```

takes me to:

```text
https://www.google.com/search?hl=en&amp;q=test
```

**Comment by facelessuser** [comment]
The Markdown converter being used is Python Markdown.  You can enter your Markdown into their test page and see it is specifically an issue with how they handle links: http://waylan.pythonanywhere.com/dingus.

An immediate solution is to use HTML syntax for links with `&` symbols: `<a href="https://www.google.com/search?hl=en&q=test">test</a>`.  HTML tags should pass through Markdown unaltered.

Long term solution is probably to open an issue at the Python Markdown repo and see what they say:  https://github.com/waylan/Python-Markdown.

There may be other ways to sidestep this issue, I just don't know one off the top of my head.  Anyways, this would need to be fixed upstream in their package so we can pick it up here.

**Comment by jrappen** [comment]
This works, thanks.
