### ISSUE TITLE
ST4074 changes to `sublime.Window.new_html_sheet`

### ISSUE THREAD

**Issue by jrappen** [facelessuser/sublime-markdown-popups#82]
* ST4074 no longer accepts `cmd` and `args` for `sublime.Window.new_html_sheet`.
* `sublime.Window.new_html_sheet` now accepts the `sublime.ADD_TO_SELECTION` flag.

**Comment by jrappen** [comment]
Source:

[![SublimeHQ Discord](https://img.shields.io/discord/280102180189634562?label=SublimeHQ%20Discord&logo=discord&style=flat-square)](https://discord.gg/D43Pecu)

and/or Changelog.

**Comment by jrappen** [comment]
Docs:

https://www.sublimetext.com/docs/api_reference.html#sublime.Window:ver-dev

**Comment by facelessuser** [comment]
Fixed by #83
