### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by jrappen** [facelessuser/sublime-markdown-popups#86]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/8577450/80917228-f16aba80-8d5d-11ea-8e99-8f40a6a75461.png">

where `#1py3 int` should have been `#!py3 int` in this section:

<https://facelessuser.github.io/sublime-markdown-popups/api/#new-html-sheet>

**Comment by facelessuser** [comment]
Thanks, I missed that!

@gir-bot add T: maintenance, C: docs
@gir-bot remove S: triage
