### ISSUE TITLE
Show HTML of popus in status bar.

### ISSUE THREAD

**Issue by mauroreisvieira** [facelessuser/sublime-markdown-popups#90]
Hi,
Any time hover an element in my code, that show a popup will render the HTML of this popup in status bar.

Exists  any way to disabled that?

![Screenshot_2020-06-25_at_10 20 06](https://user-images.githubusercontent.com/3084774/85847556-7fcc4d00-b79f-11ea-874b-14c2cfab0218.png)

**Comment by facelessuser** [comment]
mdpopups is just a wrapper around Sublime's API. It doesn't auto-popup things. If you need popups to not show up, you should disable popups in whatever plugin you are using (if they give you that option) or stop using that plugin. You can always create an issue at that plugin for them to add an option to allow disabling the popup.  So this is not an issue with mdpopups, but with whatever plugin you are using.

@gir-bot remove S: triage
@gir-bot add T: support
