### ISSUE TITLE
CSS filter causes exception

### ISSUE THREAD

**Issue by willrowe** [facelessuser/sublime-markdown-popups#94]
When I pass the following to the `css` argument none of the styles are applied and `mdpopups: Failed to retrieve scheme CSS!` is output to the console.

```
.counter {
    {{ ".foreground" | css('color') | fade(0.25) }}
    font-size: .8em;
}
```

**Comment by facelessuser** [comment]
@willrowe, what version of ST are you on? And what color scheme are you on?

I just found a small bug, at least with recent Sublime versions. Apparently, Sublime no longer returns things like `italic` and `bold` every time you call `style_for_scope`, but now it includes them only if they apply. After fixing that, `{{ ".foreground" | css('color') | fade(0.25) }}` started working for me again:

<img width="192" alt="Screen Shot 2020-08-12 at 8 27 38 AM" src="https://user-images.githubusercontent.com/1055125/90027377-b7228a80-dc75-11ea-9120-8f645383bfb3.png">

What I didn't see was the `mdpopups: Failed to retrieve scheme CSS!`, so I'd like to try your color scheme to see if there is an issue there.

**Comment by willrowe** [comment]
ST build 4081. It was working fine up until the last couple of builds. The color scheme is `DA Dark` from `DA UI`.

**Comment by facelessuser** [comment]
Cool, let me try that real quick.

**Comment by facelessuser** [comment]
@willrowe Sorry, that is an old scheme no longer publicly available. I'd have to get a link to it to test it.

**Comment by willrowe** [comment]
I'll have to test it after the fix you mentioned is released and see if that fixes it.

**Comment by facelessuser** [comment]
🤷

**Comment by facelessuser** [comment]
I deleted that scheme long ago. But I can't debug without the scheme.

**Comment by willrowe** [comment]
I really like it, it's unfortunate that they removed it. I need to find a new one that is maintained at some point. Thanks for taking a look, I will report back after testing the next release.

**Comment by facelessuser** [comment]
Well, if there are issues, there will be nothing I can do if I can't debug it, but I'll get a release out today anyways. If you have issues, and I can't debug, I'll have to close the issue regardless.

@gir-bot add S: more-info-needed

**Comment by facelessuser** [comment]
3.7.3 has been tagged, you should be able to update via `Satisfy Dependencies` command. Scheme parsing bugs will require me to debug scheme parsing, which I'm happy to do, but I'll need a failing scheme.

As far as things go right now, I am able to use filters without issues as the regression has been fixed that I experienced.

**Comment by willrowe** [comment]
That fixed it! Thanks so much for taking a look so quickly.

**Comment by facelessuser** [comment]
Glad you got it working. Wish I had caught that bug a bit sooner.
