### ISSUE TITLE
The "view" argument to md2html

### ISSUE THREAD

**Issue by rchl** [facelessuser/sublime-markdown-popups#96]
`md2html` (and probably other APIs too) needs a `view` as an argument. It looks like this is currently used to get the currently used color scheme from the view. But since the color scheme is not per-view but a global setting (I believe), would it make sense to not require the view and just get color scheme from global settings?

**Comment by facelessuser** [comment]
You can set the color scheme for a specific view. There are many plugins that do exactly this.

**Comment by rchl** [comment]
OK. No big deal. Can always pass some random view if I don't care.
